import os
import json
import re
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from dotenv import load_dotenv

load_dotenv(r"H:\rag-chatbot\.env")

OUTPUT_DIR = Path(__file__).parent / "uploads"

BG_DARK    = RGBColor(0x0D, 0x11, 0x17)
BG_CARD    = RGBColor(0x16, 0x1E, 0x2B)
ACCENT     = RGBColor(0x00, 0xB4, 0xD8)
ACCENT2    = RGBColor(0x90, 0xE0, 0xEF)
TEXT_WHITE = RGBColor(0xF0, 0xF4, 0xF8)
TEXT_MUTED = RGBColor(0x64, 0x78, 0x8B)


def _get_slides_data(question: str, chunks: list[str]) -> list:
    from groq import Groq
    groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    context = "\n\n".join(chunks)[:3000]

    prompt = f"""You are a JSON generator. Return ONLY a valid JSON array. No text, no markdown, no explanation.

Exact format:
[
  {{"title": "Slide Title Here", "bullets": ["First point", "Second point", "Third point"]}},
  {{"title": "Another Title", "bullets": ["Point one", "Point two", "Point three"]}}
]

Rules:
- ONLY the JSON array, nothing else
- 6 slides total
- 3 to 4 bullets per slide
- Short clear bullet points max 10 words each
- No asterisks no markdown no special characters

Content:
{context}"""

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=1500
    )

    raw = response.choices[0].message.content.strip()
    raw = re.sub(r'^```json\s*', '', raw)
    raw = re.sub(r'^```\s*', '', raw)
    raw = re.sub(r'\s*```$', '', raw)
    raw = re.sub(r',\s*}', '}', raw)
    raw = re.sub(r',\s*]', ']', raw)

    json_match = re.search(r'\[.*\]', raw, re.DOTALL)
    if not json_match:
        raise ValueError(f"No JSON: {raw[:200]}")

    return json.loads(json_match.group())


def _box(slide, left, top, width, height, color):
    s = slide.shapes.add_shape(1, left, top, width, height)
    s.fill.solid()
    s.fill.fore_color.rgb = color
    s.line.fill.background()
    return s


def generate_pptx(question: str, chunks: list[str]) -> str:
    slides_data = _get_slides_data(question, chunks)

    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]

    # TITLE SLIDE
    sl = prs.slides.add_slide(blank)
    _box(sl, 0, 0, prs.slide_width, prs.slide_height, BG_DARK)
    _box(sl, 0, 0, Inches(0.35), prs.slide_height, ACCENT)
    _box(sl, 0, Inches(6.8), prs.slide_width, Inches(0.7), BG_CARD)

    tb = sl.shapes.add_textbox(Inches(0.7), Inches(2.5), Inches(11), Inches(1.5))
    tf = tb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = slides_data[0]["title"] if slides_data else "Presentation"
    run.font.name = "Calibri"
    run.font.size = Pt(44)
    run.font.bold = True
    run.font.color.rgb = TEXT_WHITE

    tb2 = sl.shapes.add_textbox(Inches(0.7), Inches(4.2), Inches(8), Inches(0.5))
    p2 = tb2.text_frame.paragraphs[0]
    run2 = p2.add_run()
    run2.text = "Generated by RAG Chatbot"
    run2.font.name = "Calibri"
    run2.font.size = Pt(16)
    run2.font.color.rgb = ACCENT2

    # CONTENT SLIDES
    for idx, slide_data in enumerate(slides_data[1:]):
        sl = prs.slides.add_slide(blank)
        _box(sl, 0, 0, prs.slide_width, prs.slide_height, BG_DARK)
        _box(sl, 0, 0, prs.slide_width, Inches(1.3), BG_CARD)
        _box(sl, 0, 0, Inches(0.1), prs.slide_height, ACCENT)

        tb = sl.shapes.add_textbox(Inches(0.3), Inches(0.2), Inches(12.5), Inches(0.9))
        tf = tb.text_frame
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = slide_data.get("title", "")
        run.font.name = "Calibri"
        run.font.size = Pt(32)
        run.font.bold = True
        run.font.color.rgb = TEXT_WHITE

        _box(sl, Inches(0.4), Inches(1.5), Inches(12.5), Inches(5.6), BG_CARD)

        tb2 = sl.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(11.8), Inches(5.0))
        tf2 = tb2.text_frame
        tf2.word_wrap = True

        for i, bullet in enumerate(slide_data.get("bullets", [])):
            p = tf2.paragraphs[0] if i == 0 else tf2.add_paragraph()
            p.space_before = Pt(16)

            dot = p.add_run()
            dot.text = "●  "
            dot.font.name = "Calibri"
            dot.font.size = Pt(10)
            dot.font.color.rgb = ACCENT

            run = p.add_run()
            run.text = bullet
            run.font.name = "Calibri"
            run.font.size = Pt(20)
            run.font.color.rgb = TEXT_WHITE

        tb3 = sl.shapes.add_textbox(Inches(12.5), Inches(7.1), Inches(0.7), Inches(0.3))
        p3 = tb3.text_frame.paragraphs[0]
        p3.alignment = PP_ALIGN.RIGHT
        run3 = p3.add_run()
        run3.text = str(idx + 2)
        run3.font.size = Pt(11)
        run3.font.color.rgb = TEXT_MUTED

    output_path = OUTPUT_DIR / "presentation.pptx"
    prs.save(str(output_path))
    print(f"[pptx] Saved to {output_path}")
    return str(output_path)